### ISSUE TITLE
Log error instead of panic

### ISSUE THREAD

**Issue by caioleonhardt** [vklap/go-ddd#1]
I understand the panic at the start of the application when you are setting up the clients. IMO when you iterate over the array, it would be better idea to log/handle the error instead of panicking, it would crash the application

```go
// Start listens to the message broker and dispatches commands to be handled.
func Start() {
	pubSubClient := boostrapper.GetPubSubClientInstance()
	messages, err := pubSubClient.GetMessages(context.Background())
	if err != nil {
		panic(err)
	}
	for message := range messages {
		var command command_model.ChangeEmailCommand
		err = json.Unmarshal(message, &command)
		if err != nil {
			panic(err)
		}
		_, err = boostrapper.HandleCommand[*command_model.ChangeEmailCommand](context.Background(), &command)
		if err != nil {
			log.Printf("handle ChangeEmailCommand failed: %v", err)
		}
	}
}
```

**Comment by vklap** [comment]
Thanks a lot - I've modified to the code to log the error like so:

`func Start() {
	pubSubClient := boostrapper.GetPubSubClientInstance()
	messages, err := pubSubClient.GetMessages(context.Background())
	if err != nil {
		panic(err)
	}
	for message := range messages {
		var command command_model.ChangeEmailCommand
		err = json.Unmarshal(message, &command)
		if err != nil {
			log.Printf("failed to unmarshal ChangeEmailCommand: %v (message: %v)", err, message)
			continue
		}
		_, err = boostrapper.HandleCommand[*command_model.ChangeEmailCommand](context.Background(), &command)
		if err != nil {
			log.Printf("handle ChangeEmailCommand failed: %v", err)
		}
	}
}
`

**Comment by vklap** [comment]
Thanks a lot @caioleonhardt: you're absolutely right. 

I must admit I'm still not used to the logging mechanism in go.

Changed the code as shown below - and I hope it makes sense with regards to idiomatic go logging.

```go
func Start() {
	pubSubClient := boostrapper.GetPubSubClientInstance()
	messages, err := pubSubClient.GetMessages(context.Background())
	if err != nil {
		panic(err)
	}
	for message := range messages {
		var command command_model.ChangeEmailCommand
		err = json.Unmarshal(message, &command)
		if err != nil {
			log.Printf("failed to unmarshal ChangeEmailCommand: %v (message: %v)", err, message)
			continue
		}
		_, err = boostrapper.HandleCommand[*command_model.ChangeEmailCommand](context.Background(), &command)
		if err != nil {
			log.Printf("handle ChangeEmailCommand failed: %v", err)
		}
	}
}
```

**Comment by caioleonhardt** [comment]
Thanks for accepting the suggestion :)
